gems:
    jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lukas Zorich
tagline:          'A Jekyll theme'
description:      'Computer Science student at Pontificia Universidad Católica of Chile'
url:              http://blog.lukaszorich.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
# version:          3.2.1

github:
  repo:           https://github.com/lezorich/blog
